### ISSUE TITLE
OC: failed to load configuration

### ISSUE THREAD

**Issue by toonvanstrijp** [jaromeyer/XPS9570-Catalina#10]
I'm trying to run your latest master branch.

1. I download this repository
2. I copy the EFI folder to the EFI Partition
3. Restart my Laptop.
4. Laptop is stuck with the message: "OC: failed to load configuration"

Any idea what is going on? :)

**Comment by attilagyorffy** [comment]
> I'm trying to run your latest master branch.
> 
> 1. I download this repository
> 2. I copy the EFI folder to the EFI Partition
> 3. Restart my Laptop.
> 4. Laptop is stuck with the message: "OC: failed to load configuration"
> 
> Any idea what is going on? :)

You see, the repo currently contains multiple configurations for different models (4K touchscreen, 1080p FHD, one for DW1820 wireless, etc). I'm no OC expert but I think there may be a missing step in the documentation. You need to pick the config file that matches your model and copy that as `config.plist`. After that you will have to edit the SMBIOS, MLB, etc variables to have unique configuration for your laptop. (That's already in the docs by the way).

**Comment by jaromeyer** [comment]
exactly. i have added 4 config.plist for different setups but forgot to edit the documentation. OC will always read config.plist and unlike with clover, you cant select another config, so you have to rename the config that fits your setup to config.plist
