### ISSUE TITLE
HDMI not working

### ISSUE THREAD

**Issue by toonvanstrijp** [jaromeyer/XPS9570-Catalina#14]
I tried connecting my LG TV via HDMI but the laptop didn't recognise any screen. I'm not sure what version of HDMI the TV has. But I think it's version 2. Also I'm using the 9570 4K version.

I don't see anything mentioned about HDMI support so my guess is, that this isn't implemented yet?

**Comment by frbuccoliero** [comment]
FHD here. Connecting to a FHD monitor it works smoothly. Recognized as external screen, can drag the screen position to fix cursor while going from a screen to the other, can mirror...
Try out another HDMI cable maybe.

**Comment by frbuccoliero** [comment]
Btw in documentation branch @jaromeyer added "2560x1440@144Hz over HDMI and 4k@60Hz over DisplayPort have been tested." 
You can try downscaling screen quality to match the max allowed.

**Comment by toonvanstrijp** [comment]
@frbuccoliero I got to try it out on another screen and this time it worked flawlessly! So I guess it was either the cable, or the TV that didn't support it.
