### ISSUE TITLE
Trackpad works fine under Catalina but doens't work at all in Mojave.

### ISSUE THREAD

**Issue by andresandiah** [jaromeyer/XPS9570-Catalina#17]
As the title says. I installed Catalina and worked flawlessly with your EFI, sadly it is not working correctly with Mojave, the trackpad seems to be "disabled" (works fine in opencore). Is there anything I can do to fix the issue?

I had to go back to Mojave because of some unsupported software I have to use in mojaves (32 bit stuff)

**Comment by frbuccoliero** [comment]
Did you try using PrntScn button (right to F12) that enables/disables trackpad?

**Comment by andresandiah** [comment]
Yes. When i tried installing Catalina it was working perfectly. 
Used the same EFI to go back to Mojave and it stopped working right away.

**Comment by frbuccoliero** [comment]
Ok, i assume you have the last VoodooI2C. Try downgrading of some version https://github.com/VoodooI2C/VoodooI2C/releases

**Comment by andresandiah** [comment]
Thanks man! I tried going back to 2.3 before and didn't work. I guess i didn't go far enough. 
V 2.2 worked!
