### ISSUE TITLE
Headphone has no sound after updated to Catalina 10.15.5 (ComboJack installed)

### ISSUE THREAD

**Issue by nguyentdat23** [jaromeyer/XPS9570-Catalina#22]
First, i want to say thank for your EFI folder, it works great on my XPS. 
Yesterday, after updated MacOS to 10.15.5 my headphone jack didn't work anymore. There's no pop up windows show when i plug headphone. I tried reinstalling ComboJack but it didn't work.
Would you mind recommending a solution please?

**Comment by frbuccoliero** [comment]
Did you try updating AppleALC?

**Comment by nguyentdat23** [comment]
> Did you try updating AppleALC?

After delete folder OC and put the lastest push of Jaromeyer, headphone and everything else are working great now.

**Comment by jaromeyer** [comment]
hmm weird. so you were able to fix it by installing the latest efi from this repo?

**Comment by nguyentdat23** [comment]
> hmm weird. so you were able to fix it by installing the latest efi from this repo?

i've re-installed EFI about 2-3 times, and also tried re-installing(run file uninstall.sh then run file install.sh, not overinstall) ComboJack then my headphone worked (now system is able to recognize when headphone plugged and show a pop up).
