### ISSUE TITLE
Bluetooth problem

### ISSUE THREAD

**Issue by alexstuccer** [jaromeyer/XPS9570-Catalina#23]
Hi there. I tryed several wasy to hackintosh xps 9570, with clover and opencore. I always succeded. And always got the same bluetooth problem.
I installed 2 different dw1560, and problem persists with both.
Airdrop works just receiving. It can't see other devices. To pair, is always a pain, it often fails, and sometimes I can see several items with the same name (I have a mouse m590 from logitech, and when I try to pair, I can see 2 or 3 m590 in the list). I can't use my ipad as external screen, it always says it fails to pair. And sometimes mouse (after I reach to pair it) is laggish, and cursor jumps from one place to another on the screen.
I am waiting a dw1830 from china, but I fear problems could persist. Any suggestion?

**Comment by jaromeyer** [comment]
First of all, are you using the right config (not 1820)? Turn off BT, run `sudo rm -f /Library/Preferences/com.apple.Bluetooth.plist*`, and reboot.

**Comment by alexstuccer** [comment]
I am using the right config, not the 1820. I'll try your suggestion and will let you know. Thanks for help!

**Comment by alexstuccer** [comment]
ok, done that. Nothing changed. At the moment mouse is not giving any issue. But airdrop still works just receiving  (can't find any other device).  same problem with sidecar. The config I am using is config for 4k. My xps is a 4k, 8750h, 32 gb ram. I really can't understand what is going wrong...

**Comment by jaromeyer** [comment]
really weird. I don't have any apple devices so I have never tested airdrop, handoff, etc. myself. Have you set your own serial? To do so, follow [this guide](https://dortania.github.io/OpenCore-Desktop-Guide/post-install/iservices).

**Comment by alexstuccer** [comment]
Ok, I have my own serial. I didn't generate it with the tool named in the guide you linked. I used my old parameters generated with clover configurator (as I said, the problem was already present with clover). I already thought it could have been a smbios problem, and I tryed several with clover, nothing changed. In all my attempts I fell in the category "We’re sorry, but this serial number isn’t valid", not the one suggested as optimal in the guide. I can try again using the guide you linked, but I have some doubts: facetime works properly, is just a bluetooth problem. Overmore, since my previous post, I had some issues, with bluetooth mouse disconnecting randomly. Thanks again for your suggestion. I'll try again with that guide.

**Comment by alexstuccer** [comment]
Tryed with new smb, serial, etc, following the guide you linked. Nothing changed. Problem may be somewhere else. :S

**Comment by frbuccoliero** [comment]
Very strange, since many recomended DW1560 for native support with hackintosh. I'm using a 1820a with the fix in the repo and i also added BT4LEContinuityFixup to get Airdrop and handoff working perfectly. For other problems, i really don't know, maybe you have an unsupported version of the card (every model has "submodels" and some of them are reported working better than others)

**Comment by alexstuccer** [comment]
I must be quite unlucky then, because I tryed 2 different dw1560, and got the same issue. Anyway, a dw1830 is on the go, so as soon as it arrives, I'll let you know if swapping card will solve the problem. Thanks for your support.

**Comment by alexstuccer** [comment]
every problem I had seems to be gone with dw1830. God knows why 2 dw1560 didn't work :S

**Comment by frbuccoliero** [comment]
Very happy to hear this!! Enjoy your beast.

**Comment by BradleyHo** [comment]
Is anyone else using a Fenvi card? It's supposedly a rebranded Broadcom card. Wi-Fi works but for some reason the Bluetooth can't be activated from System Preferences. It worked on Windows 10 strangely.

**Comment by frbuccoliero** [comment]
Try here https://www.reddit.com/r/hackintosh/comments/afzwgc/fenvi_fv_t919_bluetooth_not_working/?utm_source=share&utm_medium=ios_app&utm_name=iossmf
