### ISSUE TITLE
Pls help 

### ISSUE THREAD

**Issue by marcinkk** [jaromeyer/XPS9570-Catalina#26]
Hey, how do you set the keys to adjust the screen brightness on a laptop keyboard ?? Right now it's fn + f12 and fn + key pause. My bootloader is opencore. In my laptop acer v3-371, the shortcut from adjusting the screen brightness on the keyboard is the shortcut fn + left arrow key and fn + arrow right key.

**Comment by frbuccoliero** [comment]
This repo is for the Dell XPS 9570 only, where the brightness can be adjusted with F11 and F12 keys (or fn+f11 / fn+f12 according to your bios configuration)
