### ISSUE TITLE
AppleALC.kext static noises from 3.5 mm jack

### ISSUE THREAD

**Issue by BradleyHo** [jaromeyer/XPS9570-Catalina#27]
I seem to can't get macOS to output from the 3.5 mm headphone jack. It has a bunch of static noises as well as a more muted volume. Blasting it at full volume is even worse. The internal speakers are fine, however. I wonder if there is a fix.

**Comment by frbuccoliero** [comment]
https://github.com/jaromeyer/XPS9570-Catalina#-audio

**Comment by BradleyHo** [comment]
Solved. Thanks!
