### ISSUE TITLE
Suggest Adding SMCDellSensors to repo

### ISSUE THREAD

**Issue by ideologysec** [jaromeyer/XPS9570-Catalina#29]
Thanks very much for this repo - just bought an XPS 9570, and wanted to get OpenCore up and running. Your repo made this awesomely easy.

May I suggest that you add the SMCDellSensors kext? this enables things like iStat Menus to correctly pull platform sensor data, a big win in my book!

(it hooks into VirtualSMC from my understanding).

Will report back after attempting to enable this myself on how it went.

**Comment by ideologysec** [comment]
Worked fine after adding the kext to Kexts and a section to the config file. Highly recommend!

**Comment by jaromeyer** [comment]
Thanks for your input! Actually, I have been using the kext for quite some time now, just never felt the urge to update the repo.
