### ISSUE TITLE
touchpad clicked state issue

### ISSUE THREAD

**Issue by toonvanstrijp** [jaromeyer/XPS9570-Catalina#3]
Alright this issue is hard to explain but I'll do my best.

When dragging windows I click down on the touchpad (clicky sound) and drag the window to the desired location. Then I let go the click by lifting my finger slightly, but the tip of my finger keeps touching the touchpad. It appears that `macos` still thinks I'm holding it down since for a short amount of time the windows that I was dragging follows along, then after `500ms` or so the `click` state is updated and the windows is released.

This causes a very unpleasant touchpad experience. (Still way better than normally).

I'm tested it out with different repo's and all the once that are using `voodooic2` are having this issue, so I think it's an issue with the `voodooic2` driver right?

**Comment by jaromeyer** [comment]
I know exacetly what you mean. It has been annoying the heck out of me too. But like you have said every repo has the same problem. It seems to be a bug in VoodooI2C or just the combination with exactly this trackpad. Unfortunately there is no other driver with anywhere near the performance and features of VoodooI2C.

**Comment by toonvanstrijp** [comment]
Alright then I'll report the issue over there and hope that someone knows what's going on.

**Comment by toonvanstrijp** [comment]
@jaromeyer I think this issue will be fixed soon: https://github.com/alexandred/VoodooI2C/issues/208

I'm not sure this solves it, but it sounds like it? :)

**Comment by frbuccoliero** [comment]
@ToonvanStrijp A new VoodooI2C version has been released 8 days ago, did you manage to install it to see if the problem has been solved?

**Comment by toonvanstrijp** [comment]
@frbuccoliero not yet, but I'll try it out soon :)

**Comment by jaromeyer** [comment]
with version 2.4 it seems to be even worse. now it isn't just stuck for a few seconds after releasing the physical click, but until you completely lift your finger. 2.3 worked better in that aspect. but while digging into that issue i was able to fix the high kernel_task usage when touching the trackpad. now it should always stay below 10%.

**Comment by jaromeyer** [comment]
@ToonvanStrijp just got a custom build of VoodooInput that completely fixes the drag issue and keeps kernel_task under 6%

**Comment by toonvanstrijp** [comment]
@jaromeyer did you put this kext inside your repo already?

**Comment by jaromeyer** [comment]
@ToonvanStrijp yup
