### ISSUE TITLE
Battery Stops Charging at 94%

### ISSUE THREAD

**Issue by fkscott** [jaromeyer/XPS9570-Catalina#30]
Getting decent battery life considering I have an NVME drive in the system still, but the laptop will not charge to 100%. Is anyone else having this issue?

Activity Monitor Stops at 94%
![Screen Shot 2020-09-04 at 4 18 02 PM](https://user-images.githubusercontent.com/43018547/92281966-b8d51c00-eeca-11ea-9d89-5f6ad38f439b.png)

CoconutBattery stops at 89.5% and also reads a negative battery temp

The BIOS is also reporting a charge of 89% and will not go any further.

I am running a FHD model with an i7-8750H and 16GB RAM and 512gb SSD running bios 1.15.0

The battery is the same one the laptop shipped with brand new.

Any help or insight is appreciated.

**Comment by fkscott** [comment]
Sorry guys turns out I had my BIOS set to stop charging between 85-90 🤦

**Comment by jaromeyer** [comment]
Haha glad you were able to find the issue
