### ISSUE TITLE
NVRAM variables don’t persist between reboots

### ISSUE THREAD

**Issue by attilagyorffy** [jaromeyer/XPS9570-Catalina#31]
I am having an issue whereby NVRAM variables don’t seem to persist between reboots. Having checked the OpenCore guides I followed the verification method but seems to be not working:

https://dortania.github.io/OpenCore-Post-Install/misc/nvram.html#verifying-if-you-have-working-nvram

Can anyone with the current EFI in the repo reproduce the verification as intended?

Thanks in advance.

**Comment by jaromeyer** [comment]
Hm thats very weird. Have you done any changes to the config.plist under the NVRAM section?

**Comment by attilagyorffy** [comment]
@jaromeyer My bad, had some updates to the repository, mainly kernel extension upgrades etc. Once I reverted to your version (besides having my personal MLB, SystemSerialNumber and SystemUUID) it seems to be working again.
