### ISSUE TITLE
Hanging on install (Big Sur)

### ISSUE THREAD

**Issue by Fyobl** [jaromeyer/XPS9570-Catalina#33]
![6A73E86A-36BC-4438-BD32-B7B465B78720](https://user-images.githubusercontent.com/66086323/93513469-cc966e80-f91d-11ea-8dcd-71798a2b0460.jpeg)

Stuck here after clicking the bootable installer via usb.

My system

Dell XPS 15 9570
i7 8750H
32GB ram
1TB NVMe
DW1830 WiFi

**Comment by jaromeyer** [comment]
so youre not even reaching the apple loading screen or installer gui? what ssd are you using? and maybe try disabling verbstub.kext. its only needed to fix some audio issues.

**Comment by Fyobl** [comment]
I don’t get to the installer gui. I can see the apple logo if I take -v out of boot arg.

I have KXG50ZNV1T02 NVMe Toshiba.

I’ll try what you suggested and get back to tiu

**Comment by Fyobl** [comment]
Disabled verbstub.kext but no change still stalls.

Any other suggestions?

**Comment by attilagyorffy** [comment]
@Fyobl have you had any success in installing Catalina using the EFI provided in the repo or is Big Sur your first attempt? Look up your SSD and its controller to see if others have had any success.

**Comment by Fyobl** [comment]
@attilagyorffy i have Catalina installed fine with this config. Just issues with Big Sur.

**Comment by jaromeyer** [comment]
Hm weird. Where does it get stuck without VerbStub? I will check tomorrow if I messed up when uploading the EFI or something

**Comment by Fyobl** [comment]
> Hm weird. Where does it get stuck without VerbStub? I will check tomorrow if I messed up when uploading the EFI or something

It didn’t make any difference disabling verbstub.kext than I did having it enabled. Was still the same outcome and same screen.

**Comment by jaromeyer** [comment]
that makes no sense because in you screenshot the last line is about VerbStub

**Comment by Fyobl** [comment]
> that makes no sense because in you screenshot the last line is about VerbStub

I will double check and report back

**Comment by Fyobl** [comment]
@jaromeyer 
![DB9822F4-4894-4A74-A51C-CF1E7CE39DE6](https://user-images.githubusercontent.com/66086323/93689429-5bde8600-fac6-11ea-99f0-1829f5e68c56.jpeg)

So this is we’re it hangs with verbstub.kext disabled.

**Comment by Fyobl** [comment]
![image](https://user-images.githubusercontent.com/66086323/93689961-63ecf480-facb-11ea-8131-d0cfc63fe508.jpg)

Second attempt and it’s stuck here.

**Comment by Fyobl** [comment]
@jaromeyer have you had chance to look over the EFI ?

**Comment by jaromeyer** [comment]
im currently using the exact config from my repo and everything is working fine. check if all kexts are up-to-date

**Comment by Fyobl** [comment]
@jaromeyer 
All kexts are up to date.

I have been looking over the config for days now trying to find solutions.

Did you do an upgrade from Catalina or a clean install?

**Comment by jaromeyer** [comment]
did a clean install onto a separate partition and then updated my main partition from catalina. both work fine

**Comment by Fyobl** [comment]
@jaromeyer 

That’s what I’ve done.

In Catalina I downloaded the update and made a new container in my partition for big sur.

**Comment by Fyobl** [comment]
@jaromeyer 

I’m going to try a different method of installing Big Sur.

Going to use a VM image and clone it to my partition and see if it will boot into it from there.

That way I skip the whole install process.

Will report back once it’s done.

**Comment by Fyobl** [comment]
@jaromeyer 

Okay some progress!

I did a copy of the VM Big Sur and have cloned it to my internal drive.

It loads all the way and I can hear Siri talking to me to get the MacBook set up but it’s stuck in verbose mode and won’t come off that screen. I have taken the -v out of boot arg and it does the same thing but sits on the apple logo.

Any suggestions?

**Comment by jaromeyer** [comment]
4k or fhd?

**Comment by Fyobl** [comment]
4K

**Comment by Fyobl** [comment]
![image](https://user-images.githubusercontent.com/66086323/93935102-056a8500-fd1c-11ea-80f7-bd61ce6dc002.jpg)

@jaromeyer  it gets to here and I can hear Siri but this won’t go?

**Comment by jaromeyer** [comment]
You probably need do patch your EDID to use the internal 4k screen. Can you try to boot with a screen connected via HDMI?

**Comment by Fyobl** [comment]
@jaromeyer 
Okay it shows a screen when I boot with my tv plugged in via hdmi.

So what is it I need to do to get the screen to work on my laptop?

**Comment by jaromeyer** [comment]
You need to read my reply😅 Search for "Big Sur XPS 4K EDID" or something. If you cant find a solution, ill tell you what to do tomorrow. Im way too tired rn

**Comment by Fyobl** [comment]
@jaromeyer 

I appreciate your time and effort it helping me resolve this.

I haven’t had to patch an EDID before but looking at the guides I have found there’s a few possible ways to do it.

I have found my screens EDID but what solution is best to use?

**Comment by jaromeyer** [comment]
send me the output of `ioreg -lw0 | grep -i "IODisplayEDID"`and ill give you a patched EDID that you can add here:
`Devices>Properties>PciRoot(0x0)/Pci(0x2,0x0)>AAPL00,override-no-connect`

**Comment by Fyobl** [comment]
@jaromeyer 

benjaminsmith@MacBook-Pro ~ % ioreg -lw0 | grep -i "IODisplayEDID"
    | |   | | |       "IODisplayEDID" = <00ffffffffffff004d108d1400000000051c0104a52213780e1518aa5335bc250c5054000000010101010101010101010101010101014dd000a0f0703e803020350058c210000018000000000000000000000000000000000000000000fe00464e564452804c513135364431000000000002410328011200000b010a2020005d>

**Comment by jaromeyer** [comment]
ok so using propertree under `Devices>Properties>PciRoot(0x0)/Pci(0x2,0x0)` create a new entry called `AAPL00,override-no-connect` with the type data. Then copy the following patched EDID:
`00ffffffffffff004d108d1400000000051c0104a52213780e1518aa5335bc250c505400000001010101010101010101010101010101a6a600a0f0703e803020350058c210000018000000000000000000000000000000000000000000fe00464e564452804c513135364431000000000002410328011200000b010a2020002e`

**Comment by Fyobl** [comment]
@jaromeyer 
![image](https://user-images.githubusercontent.com/66086323/94023555-41e6c100-fdae-11ea-9c9b-5790d6afbe10.jpg)

That’s done the trick!

Thank you for you help in resolving this.

**Comment by Fyobl** [comment]
Unresponsive trackpad after reboot? Any ideas?
@jaromeyer

**Comment by jaromeyer** [comment]
make sure you havent disabled it using the printscreen button. otherwise pls open a separate issue
