### ISSUE TITLE
Trackpad Issue

### ISSUE THREAD

**Issue by Fyobl** [jaromeyer/XPS9570-Catalina#35]
The trackpad isn't responding in some cases.

Works in Catalina fine.

Works sometimes on Big Sur I have to restart and while verbose is loading I have to move my fingers over the trackpad for it to pick up on boot.

If I don't move my fingers over the trackpad and I get to the welcome screen I get an unresponsive trackpad.

**Comment by Fyobl** [comment]
I have checked the "print screen" button and that's not the issue.

**Comment by frbuccoliero** [comment]
Happened a couple times on Catalina, i cleared nvram and restarted with no issues.

**Comment by Fyobl** [comment]
@frbuccoliero 

Have tried that no success.

**Comment by frbuccoliero** [comment]
Try with an older release of the kext VoodooI2C, maybe the new release is having some issues with Big Sur.

**Comment by Fyobl** [comment]
@frbuccoliero 

Have replaced the kext and everything seems okay for now.

Will test it out over the next few days and report back.

**Comment by Fyobl** [comment]
well it works but its very jumpy... randomly jumping while I scroll round the screen

@jaromeyer 
@frbuccoliero

**Comment by frbuccoliero** [comment]
Are you sure it's not an hardware issue?  Did you have the chance to test it properly in windows?

**Comment by Fyobl** [comment]
> Are you sure it's not an hardware issue? Did you have the chance to test it properly in windows?

@frbuccoliero 

Works fine in windows and in Catalina, Its strange... can't work out what's causing it.

**Comment by frbuccoliero** [comment]
I don't know. Report carefully this problem on a issue on VoodooI2C 's repo.  I'm still pretty sure it's a kext problem.

**Comment by Fyobl** [comment]
@frbuccoliero @jaromeyer 

Solved

Disabling the touchscreen by replacing the SSDT-TPDX.aml with the one in resources folder and touchpad is now working without jumping.

**Comment by frbuccoliero** [comment]
Awesome! :D
