### ISSUE TITLE
Big Sur update beta 9 not working

### ISSUE THREAD

**Issue by toonvanstrijp** [jaromeyer/XPS9570-Catalina#40]
I'm trying to update my Big Sur installation but each time I hit `update now` it doesn't work. Any idea how to resolve this?

The error I got is: `The volume cannot be used because it is not snapshot booted.`

<img width="780" alt="Screenshot 2020-09-30 at 23 59 15" src="https://user-images.githubusercontent.com/11893063/94744271-f9fd0680-0378-11eb-9c75-ef467254575f.png">

```
❯ sudo softwareupdate -aiR
Software Update Tool

Finding available software
Downloading macOS Big Sur Beta 9
Downloading: 100.00%
Failed to download & prepare update: Error Domain=SUMacControllerError Code=7722 "[SUMacControllerErrorPreflightPrerequisiteCheckFailed=7722] Failed to perform PreflightPrerequisite operation: com.apple.BuildInfo.preflight.error:6 | The volume cannot be used because it is not snapshot booted.: [com.apple.BuildInfo.preflight.error:6]" UserInfo={NSUnderlyingError=0x600002e6e220 {Error Domain=com.apple.BuildInfo.preflight.error Code=6 "The volume cannot be used because it is not snapshot booted." UserInfo={BIPreflightAlternateInstallerRecommended=true, NSLocalizedFailureReason=The volume cannot be used because it is not snapshot booted., NSLocalizedDescription=The volume cannot be used because it is not snapshot booted.}}, SUMacControllerErrorIndicationsMask=0, NSDebugDescription=[SUMacControllerErrorPreflightPrerequisiteCheckFailed=7722] Failed to perform PreflightPrerequisite operation: com.apple.BuildInfo.preflight.error:6 | The volume cannot be used because it is not snapshot booted.: [com.apple.BuildInfo.preflight.error:6], NSLocalizedDescription=Current device configuration and target are invalid for installation in the current state. Please try again.}
```

**Comment by ideologysec** [comment]
Interesting, looks like they're turning on the actual security model for Big Sur with this. I suspect OpenCore will need to be updated to deal with this; otherwise poking around the new security options in OpenCore 0.6.1 might help you out:

https://dortania.github.io/OpenCore-Post-Install/universal/security/applesecureboot.html#apecid

I would also see if you can download the full installer from somewhere, and create a new bootable installer to install Big Sur beta 9 offline with and see what happens - after making a backup of course.

**Comment by toonvanstrijp** [comment]
@ideologysec I solved it somehow by downloading the `Big Sur` install app (as you mentioned the offline installer, don't know how tho haha).

**Comment by jaromeyer** [comment]
run into the same problem when trying to update from beta 8 to 9. like ideologysec already mentioned, disabling `SecureBootModel` solved it for me

**Comment by eorsinijr** [comment]
@jaromeyer @ideologysec 
> run into the same problem when trying to update from beta 8 to 9. like ideologysec already mentioned, disabling `SecureBootModel` solved it for me

> Interesting, looks like they're turning on the actual security model for Big Sur with this. I suspect OpenCore will need to be updated to deal with this; otherwise poking around the new security options in OpenCore 0.6.1 might help you out:
> 
> https://dortania.github.io/OpenCore-Post-Install/universal/security/applesecureboot.html#apecid
> 
> I would also see if you can download the full installer from somewhere, and create a new bootable installer to install Big Sur beta 9 offline with and see what happens - after making a backup of course.

I've downloaded OPenCore 0.6.1 but have never used it before.  Can you walk me through how to do this disable?  I'm having issues going from beta 8 to 9 and nothing has worked...

**Comment by ideologysec** [comment]
@eorsinijr I would recommend forgetting about OpenCore if you're using Clover, and just downloading the newest/latest Big Sur Install.app or the combo update.

Edit: this is an OpenCore repo, are you using this repo on an XPS 9570? What specifically are you having trouble with? Disabling the security options is done in the config.plist. If that sentence doesn't make sense to you, I suggest diving in to how OpenCore works a little bit more deeply and working from there.

**Comment by ideologysec** [comment]
> @ideologysec I solved it somehow by downloading the `Big Sur` install app (as you mentioned the offline installer, don't know how tho haha).

@ToonvanStrijp the same way you'd make a regular OpenCore bootable installer: https://support.apple.com/en-us/HT201372 and then adding all of the OpenCore bits to the EFI partition so it will boot, and then booting from the USB and basically performing an install on top of the existing macOS install on your internal partition (which should preserve data)

**Comment by jaromeyer** [comment]
@eorsinijr what exact problem are you facing?

**Comment by eorsinijr** [comment]
> @eorsinijr what exact problem are you facing?

> @eorsinijr I would recommend forgetting about OpenCore if you're using Clover, and just downloading the newest/latest Big Sur Install.app or the combo update.
> 
> Edit: this is an OpenCore repo, are you using this repo on an XPS 9570? What specifically are you having trouble with? Disabling the security options is done in the config.plist. If that sentence doesn't make sense to you, I suggest diving in to how OpenCore works a little bit more deeply and working from there.

I'm running a MacBook Pro 2020 16inch, with an i9 and 32gb of mem, so it's no slouch.  However running the beta I would get overheating issues and random shutdowns/reboots and I couldn't figure out why.  I even wiped, went back to reg software, then back to the beta and still had the issues without many of my normal apps.  When trying to upgrade to beta 9, it would fail repeatedly, but not give a reason why. I tried through the software, then CLI.  I'm back on Catalina for now but want to go back to the beat (calendar won't let me do some things since it was on the higher version) but I'm nervous about overheating again.

**Comment by jaromeyer** [comment]
Weird. I did a OTA from Catalina to Beta 3 I think and then OTA through all the following Betas and never faced any problems. OTA works like on a real Mac for me

**Comment by Fyobl** [comment]
Same for me.

Only issue I have was going from beta 8 to 9 but that’s because of SecureBootModel.

Going from 9 to 10 worked fine aswell.

**Comment by eorsinijr** [comment]
> Weird. I did a OTA from Catalina to Beta 3 I think and then OTA through all the following Betas and never faced any problems. OTA works like on a real Mac for me

> Same for me.
> 
> Only issue I have was going from beta 8 to 9 but that’s because of SecureBootModel.
> 
> Going from 9 to 10 worked fine aswell.

Weird. Everything worked great minus the random reboots and heating. You guys never had those issues? I want to get back on it cause I loved the integration with iOS14 and iPad14

**Comment by Fyobl** [comment]
No random reboots and no heating issues for me... but I have taken my laptop apart and put better grade thermal paste in it.
