### ISSUE TITLE
Left cliking doesnt work properly on fresh install

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [jaromeyer/XPS9570-Catalina#41]
I did a fresh install of catalina 15.7 but left clicking on the touchpad on any application doesnt work. It 'zooms' the screen. Right clicking does work properly on the menu-bar on top does seem to fuction like expected.

**Comment by MathiasDeWeerdt** [comment]
Note: Some reboots the touchpad does straight up nothing, rebooting it again works perfectly.

**Comment by toonvanstrijp** [comment]
@MathiasDeWeerdt try disabling the force-touch option
<img width="780" alt="Screenshot 2020-10-01 at 10 04 05" src="https://user-images.githubusercontent.com/11893063/94783853-94873500-03cd-11eb-9d8e-a587d281ffcf.png">

Same for my on Big sur, sometimes the touchpad doesn't do anything (well..... veryyyyy slowly, like it moves once a minute for a few pixels). After a reboot it works fine.

**Comment by MathiasDeWeerdt** [comment]
@ToonvanStrijp Awesome! That worked. Thanks man

**Comment by toonvanstrijp** [comment]
@MathiasDeWeerdt one tip:

If you use two fingers for right clicking disable the `Smart zoom` option under the `Scroll & Zoom` tab. (Smart Zoom adds a delay to right clicking)

**Comment by Fyobl** [comment]
> Same for my on Big sur, sometimes the touchpad doesn't do anything (well..... veryyyyy slowly, like it moves once a minute for a few pixels). After a reboot it works fine.

Disabling the touchscreen fixed this issue for me.

**Comment by toonvanstrijp** [comment]
@Fyobl how did you disable it? Cause I've followed the instruction. But sometimes this problem still occurs.

**Comment by Fyobl** [comment]
@ToonvanStrijp 

[Here](https://github.com/jaromeyer/XPS9570-Catalina#-touchscreen)

Just swap the files over in you EFI and reboot.

**Comment by toonvanstrijp** [comment]
@Fyobl yeah that's what I did. But the problem still occurs occasionally :grimacing:
