### ISSUE TITLE
Can anyone make iServices work properly?

### ISSUE THREAD

**Issue by khoa-nv** [jaromeyer/XPS9570-Catalina#42]
I already change Serial, MLB, UUID but I still cannot sign in to iMessage or Facetime?

**Comment by frbuccoliero** [comment]
I also had a lot of trouble with imessage and stuff, check in the readme the link to the full procedure to reset keychain and start from scratch

**Comment by khoa-nv** [comment]
> I also had a lot of trouble with imessage and stuff, check in the readme the link to the full procedure to reset keychain and start from scratch

I follow the link and go a 404 error :((( The post was moved!

**Comment by frbuccoliero** [comment]
Oh sorry. Dortania moved the whole post-install docs to a new main page. Here it's the new link: [CLICK HERE](https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#customer-code-error)

**Comment by khoa-nv** [comment]
> Oh sorry. Dortania moved the whole post-install docs to a new main page. Here it's the new link: [CLICK HERE](https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#customer-code-error)

Thank you, bro! Have you finished activating iServices for your device?

**Comment by frbuccoliero** [comment]
Yes i have all working perfectly

**Comment by khoa-nv** [comment]
> Yes i have all working perfectly

Thank you, bro.

**Comment by Fyobl** [comment]
@frbuccoliero sorry I know this is closed but I been looking at getting this working.

Do we have to emulate the NVRAM on our XPS?

**Comment by frbuccoliero** [comment]
Are we still talking about iServices problems? Btw no, we don't.

**Comment by Fyobl** [comment]
@frbuccoliero 

Yes still on the iService issue.

I can't seem to get the command to show if NVRAM is working to work.

`root@MacBook-Pro ~ # sudo nvram -c
nvram: Error clearing firmware variable csr-active-config: (iokit/common) not permitted`

SIP disabled with <67000000> in config.

Just didn't know if I needed to do this step but if we have NVRAM I guess I don't need to worry about this step?

**Comment by frbuccoliero** [comment]
Yeah just skip that

Francesco Buccoliero
Software Developer
Engineering Student @ PoliMi
    @frbuccoliero

**Comment by Fyobl** [comment]
I have done all steps in the guide suggested but the issue I get is:

Open messager
Login with my details
shows loading box then goes to the messages screen (Doesn't show me any of messages)
goes back to login screen

**Comment by Fyobl** [comment]
@frbuccoliero 

It states my WiFi can be en0 but others suggest I should do fakeethernet.kext?

how is it set up your end?

**Comment by khoa-nv** [comment]
> I have done all steps in the guide suggested but the issue I get is:
> 
> 
> 
> Open messager
> 
> Login with my details
> 
> shows loading box then goes to the messages screen (Doesn't show me any of messages)
> 
> goes back to login screen

Yeap, I got the same problem!

**Comment by Fyobl** [comment]
@frbuccoliero 

I have also added ROM into my config and input my MAC address without the ":"

Any suggestions ?

**Comment by frbuccoliero** [comment]
About en0, it should be set by default. In hackintool i can check that it's en0 built in. If it's not for you there's something wrong with wlan configuration. You should not need any extra kext for that.

About the error you get, it's exactly what happens if there are left traces of previous imessage attempts. I suggest you to clear all your smbios stuff, clear nvram, do the cleaning procedure again and change completely smbios (serial and the other stuff)

**Comment by frbuccoliero** [comment]
Make sure to follow carefully the keychain part of the guide (https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#cleaning-up-your-appleid) deleting ALL the occurencies that match the ones in the black box. This step is crucial, i missed a few of them in the keychain and got your same error

**Comment by jaromeyer** [comment]
what wifi card are you using?

**Comment by Fyobl** [comment]
@frbuccoliero  I will do this now and report back once done.

@jaromeyer I have the DW1830

**Comment by Fyobl** [comment]
@frbuccoliero 

Done everything from scratch and still no joy.

I get a message asking me to put in my 6 digit code then it goes back to login screen.

**Comment by frbuccoliero** [comment]
There is something wrong somewhere. Show me your hackintool > system > peripherals

**Comment by Fyobl** [comment]
@frbuccoliero 

<img width="1062" alt="Screenshot 2020-10-07 at 16 00 20" src="https://user-images.githubusercontent.com/66086323/95348863-5d75bf80-08b6-11eb-9a9e-5dba7506afa1.png">

**Comment by khoa-nv** [comment]
I had the same problem with @Fyobl. Sometimes it asks for a code, other times it doesn't, after a while of loading it come back to the login screen. But the weird thing is it happens to all my accounts except for one I can fully activate Facetime :))))

**Comment by frbuccoliero** [comment]
I have no idea then, if you followed all the procedure it should just work. @jaromeyer anything to add?

**Comment by Fyobl** [comment]
@jaromeyer any ideas dude?

**Comment by khoa-nv** [comment]
@frbuccoliero Did you change the serial number and fix iService before you make a clean installation or did you install macOS and fix the iService after?

**Comment by frbuccoliero** [comment]
I first installed macos with a non working wifi card so when i tried using imessage i got error. Then changed wifi card to 1820a but without cleaning anything and still got errors. At the end when i cleaned everything and started from scratch with new serial and new everything it worked smoothly. All of this after installing macos.

**Comment by khoa-nv** [comment]
> I first installed macos with a non working wifi card so when i tried using imessage i got error. Then changed wifi card to 1820a but without cleaning anything and still got errors. At the end when i cleaned everything and started from scratch with new serial and new everything it worked smoothly. All of this after installing macos.

What does it mean of "cleaned everything and started from scratch"? Is it format your hard disk and reinstall macos?

**Comment by frbuccoliero** [comment]
no, cleaned the previous attempts, changed serial and the others. never reinstalled macos

**Comment by khoa-nv** [comment]
> no, cleaned the previous attempts, changed serial and the others. never reinstalled macos

:( I have tried many times, I think the problem is with my account. I have an account can sign in but others can't. I also call to Apple Support but can't solve my problem!

**Comment by Fyobl** [comment]
I have tried using a new account t and I also get the same error.

**Comment by frbuccoliero** [comment]
Try linking a credit card to the apple account.

**Comment by khoa-nv** [comment]
> I have tried using a new account t and I also get the same error.

did you try with an old account that was created before 2017?

**Comment by frbuccoliero** [comment]
My account was very old, 2015 i think.

**Comment by khoa-nv** [comment]
> My account was very old, 2015 i think.

I tried with 2 account created before 2017 and it working properly :))) I think that is the problem.

**Comment by Fyobl** [comment]
I don’t have an account that’s older than 2017

**Comment by khoa-nv** [comment]
> My account was very old, 2015 i think.

How many accounts did you create with your phone number?

**Comment by jaromeyer** [comment]
sorry guys im not using iServices myself

**Comment by frbuccoliero** [comment]
> > My account was very old, 2015 i think.
> 
> How many accounts did you create with your phone number?

Just one. My account is also linked to an iphone since 2015, has a credit card linked since 2015 and few purchases trough apple. So on apple side it's a perfect apple id, it was really impossible for me to believe that it wasn't working on this hackintosh, since i had it working on other two of them.

**Comment by ideologysec** [comment]
Had no issues - installed macOS with DW1830 card, generated serials per the guide, used an AppleID that is very old (my main account, 10+ years at this point), flawless. (2-step verification enabled).

What does the age of an AppleID have to do with anything?

**Comment by frbuccoliero** [comment]
Some kind of apple server-side validation, empirically it works better with older accounts
