### ISSUE TITLE
XPS 9570 i7 4k touch blackout after big sur upgrade from catalina 

### ISSUE THREAD

**Issue by gknyce** [jaromeyer/XPS9570-Catalina#48]
Hello thanks for your time and work, much appreciated. I have a problem. I install Catalina using the repo, screen works fine and is not blackout. After that when I try to install big sure beta 9 with the installer on USB, when the laptop reboot to finish the installation I get the apple background and looks like it finishes but after that I can't see anything on the screen, it goes black. I'm using XPS 9570 i7 4k 1tb Toshiba m.2 touch.

P.S. I have read through the issues tab on you repo and see similar issues but when I make changes the laptop still blackout.

**Comment by Fyobl** [comment]
Have you added the EDID into your config?

#33 read this it might help

**Comment by gknyce** [comment]
> Have you added the EDID into your config?
> 
> #33 read this it might help

I did last week, but I scrapped that. I added pci location from using hackintool. HDMI works with external monitor.

**Comment by Fyobl** [comment]
Have you tried to use verbose mode with the debug versions of opencore? Maybe something in the logs will help

**Comment by jaromeyer** [comment]
then you probably did the EDID patch wrong

**Comment by gknyce** [comment]
Using hackintool could I past my EDID here for you to patch it for me? The info from the tool says that the frame buffer matches with intel 655 and not the 630 iGPU.

**Comment by Fyobl** [comment]
@gknyce

send me the output of `ioreg -lw0 | grep -i "IODisplayEDID"`and ill give you a patched EDID that you can add here:
`Devices>Properties>PciRoot(0x0)/Pci(0x2,0x0)>AAPL00,override-no-connect`

Copied from @jaromeyer

**Comment by gknyce** [comment]
| |   | | |       "IODisplayEDID" = <00ffffffffffff004d108d1400000000051c0104a52213780e522daa5335bc250c5155000000010101010101010101010101010101014dd000a0f0703e803020350058c210000018000000000000000000000000000000000000000000fe00464e564452804c513135364431000000000002410328011200000b010a20200009>

**Comment by Fyobl** [comment]
@gknyce 

Im sure you just add `00ffffffffffff004d108d1400000000051c0104a52213780e522daa5335bc250c5155000000010101010101010101010101010101014dd000a0f0703e803020350058c210000018000000000000000000000000000000000000000000fe00464e564452804c513135364431000000000002410328011200000b010a20200009`

here

<img width="1256" alt="Screenshot 2020-10-26 at 16 41 25" src="https://user-images.githubusercontent.com/66086323/97201831-cca24d80-17aa-11eb-9219-8d0063742570.png">

reset NVRAM and try again

@jaromeyer is that correct?

**Comment by gknyce** [comment]
Thanks but it does not work. Should the upgrade to Big Sur from Catalina happen on the internal drive or external USB, meaning to copy it to the internal name or just from the usb.

**Comment by Fyobl** [comment]
I just used the system update tool... but I got the black screen issue but with the EDID patch It worked like a charm

**Comment by jaromeyer** [comment]
@gknyce Heres your patched EDID: `00ffffffffffff004d108d1400000000051c0104a52213780e522daa5335bc250c515500000001010101010101010101010101010101a6a600a0f0703e803020350058c210000018000000000000000000000000000000000000000000fe00464e564452804c513135364431000000000002410328011200000b010a202000da`
@Fyobl you have to patch it before injecting, otherwise it will do absolutely nothing because it will replace the original EDID with itself.

**Comment by jaromeyer** [comment]
also i did a normal OTA from Catalina to Big Sur.

**Comment by Fyobl** [comment]
@jaromeyer How do i patch it ?

**Comment by jaromeyer** [comment]
edit 4 bytes and then recalculate the checksum. heres a great [python script](https://paste.ubuntu.com/p/BNpzrQCMRg/)

**Comment by gknyce** [comment]
Thanks @jaromeyer @Fyobl for your help, I finally got it working. I have EFI to boot Big Sur, I added vit9696 boot arg and also the patches EDID.

**Comment by imraan-go** [comment]
> Thanks @jaromeyer @Fyobl for your help, I finally got it working. I have EFI to boot Big Sur, I added vit9696 boot arg and also the patches EDID.

After patchid EDID, is it running at 48 Hz or 60 Hz?

**Comment by gknyce** [comment]
Resolution is 4k, but then UI looks like 1080 @48hz

**Comment by jaromeyer** [comment]
Pretty sure its 48Hz only for now

**Comment by imraan-go** [comment]
> Pretty sure its 48Hz only for now

How does it feel with 48Hz? is it usable? i think i'll feel dizzy running 48hz for a long time 🤕

**Comment by jaromeyer** [comment]
> > Pretty sure its 48Hz only for now
> 
> 
> 
> How does it feel with 48Hz? is it usable? i think i'll feel dizzy running 48hz for a long time 🤕 

Dunno, i have the FHD model

**Comment by imraan-go** [comment]
This https://github.com/acidanthera/WhateverGreen/commit/9b68d9fba30a08f72dfbfe4cf82f674039f531ac shoud fix the issue. @jaromeyer Can you the master branch of WEG a try?

**Comment by jaromeyer** [comment]
@imraan-go thanksfor the heads up. i will have a look at it.
