### ISSUE TITLE
airdrop and sidecar?

### ISSUE THREAD

**Issue by Berto995** [jaromeyer/XPS9570-Catalina#49]
does sidecar and airdrop work with DW1560?

**Comment by frbuccoliero** [comment]
I have DW1820A and they work well. DW1560 is more expensive and performant so in theory it should work too.

**Comment by Fyobl** [comment]
I have the DW1830 and it works fine.

I also had the DW1560 before that and it worked fine.

**Comment by jaromeyer** [comment]
dw1820a here and sidecar with the latest iPad Pro works flawlessly (Big Sur and iPad OS 14)
