### ISSUE TITLE
Big Sur crashes when booting

### ISSUE THREAD

**Issue by Skraldefar** [jaromeyer/XPS9570-Catalina#50]
Hi

On my 4k i7 XPS 9570 i have gotten to the point where I could install Big Sur with the help of edid patch.
Now though, when booting from the SSD, the computer seems to crash at the following output:
calling npo_policy_init for ASP
calling npo_policy_initbsd for

And then it hangs.

Does anyone have any suggestions on what can cause this? I can run Catalina absolutely fine

**Comment by Fyobl** [comment]
What SSD are you using?

**Comment by Skraldefar** [comment]
> What SSD are you using?

A Samsung Evo 970 1tb

**Comment by jaromeyer** [comment]
Looks like it is security related. The darwin-xnu sourcecode suggests that it happens during "Per-policy initialization"

**Comment by Skraldefar** [comment]
I can take a video of the verbose output, if you can use that?`

**Comment by Skraldefar** [comment]
https://photos.app.goo.gl/vpqNfgz7QYcnQ65B6

**Comment by jaromeyer** [comment]
are you sure it crashes or does it just disable display output because you didn't patch your EDID properly? have you tried attaching an external monitor via HDMI prior to booting?

**Comment by Skraldefar** [comment]
I don't think so, as the computer restarts when this happens. As far as the edid patch, i have tried it, but dont know if i have done it right though...

**Comment by Skraldefar** [comment]
Also happens when external monitor is attached. The point at which it crashes seems to be random though

**Comment by Fyobl** [comment]
Have you patched your EDID?

**Comment by Skraldefar** [comment]
I have run a script i found to find the values, it gave me the following, where i used the modified EDID:

Display EDID: 00ffffffffffff004d108d1400000000051c0104a52213780eab87a95335bc250c5153000000010101010101010101010101010101014dd000a0f0703e803020350058c210000018000000000000000000000000000000000000000000fe00464e564452804c513135364431000000000002410328011200000b010a20200059

Modified EDID: 00ffffffffffff004d108d1400000000051c0104a52213780eab87a95335bc250c515300000001010101010101010101010101010101a6a600a0f0703e803020350058c210000018000000000000000000000000000000000000000000fe00464e564452804c513135364431000000000002410328011200000b010a2020002a

data: AP///////wBNEI0UAAAAAAUcAQSlIhN4DquHqVM1vCUMUVMAAAABAQEBAQEBAQEBAQEBAQEBpqYAoPBwPoAwIDUAWMIQAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gBGTlZEUoBMUTE1NkQxAAAAAAACQQMoARIAAAsBCiAgACo=

**Comment by jaromeyer** [comment]
maybe have a look at #52

**Comment by Skraldefar** [comment]
This worked. Thank you :)
