### ISSUE TITLE
Black screen after upgrade from Catalina to Big Sur

### ISSUE THREAD

**Issue by KSYMEK** [jaromeyer/XPS9570-Catalina#51]
After upgrade to Big Sur I have black screen. On this stage even in verbose mode I also have black screen so I think I have issue with monitor output or iGPU settings. I am using defualt 4k settings. Any ideas?

**Comment by Fyobl** [comment]
Have you patched your EDID?

**Comment by Fyobl** [comment]
https://github.com/jaromeyer/XPS9570-Catalina/issues/33

**Comment by KSYMEK** [comment]
No I don't. Is there any way to achieve it from windows?

**Comment by Fyobl** [comment]
@jaromeyer can you work your magic here?

**Comment by jaromeyer** [comment]
Give me your original EDID and I can provide a patched version. There should be programs to extract it from Windows or otherwise you should be able to boot the Catalina recovery and use the terminal there.

**Comment by KSYMEK** [comment]
Okay I just formatted my computer and reinstalled Catalina and patched EDID but now after update to Big Sur I have this issues. After that computer reboots. I have no issues to enter recovery mode.

![IMG_0008](https://user-images.githubusercontent.com/15861603/98238193-4df59f00-1f66-11eb-806e-00ebdb2f59aa.jpg)
![IMG_0009](https://user-images.githubusercontent.com/15861603/98238198-4f26cc00-1f66-11eb-9414-69770ede92e9.jpg)

**Comment by KSYMEK** [comment]
Okay for now I fixed issue by adding NVM efi driver.** I'll keep issue open if I occur any new issue similar to this issue.
