### ISSUE TITLE
KP updating from Catalina to Big Sur

### ISSUE THREAD

**Issue by frbuccoliero** [jaromeyer/XPS9570-Catalina#52]
I was waiting for the final release to update to big sur, also looking at the discouraging issues you early-adopters faced with the betas. I updated OC to 0.6.3 and all kexts, all working good. I then proceeded to update to Big Sur and when booting the "macOS installer" entry from the picker... here the kernel panic
https://youtu.be/6vHIrUI1cQQ

My model is 1080p , no-touch so i don't need that screen patch that is so important for 4k models. Already contacted the bigboss Jaro but I hope you other guys of this little xps family can give me a shot bout what to do :D

**Comment by Fyobl** [comment]
What Kexts are you using?

Also could you upload your config.plist.

I personally am using OC 0.6.1 and have not updated my Kexts since that build.

Later on tonight I will pop 0.6.3 onto a USB and update all Kexts to test and see if I get the same issue.

**Comment by frbuccoliero** [comment]
Here they are, i config i just removed serial and other personal stuff.

![Schermata 2020-11-13 alle 15 54 01](https://user-images.githubusercontent.com/14348908/99085428-73b71f80-25c8-11eb-8912-7b42c294b50c.png)
[config.plist.zip](https://github.com/jaromeyer/XPS9570-Catalina/files/5537504/config.plist.zip)

**Comment by Fyobl** [comment]
Thanks. I will use your config and kexts to try and boot into my Big Sur later on and see if I’m getting the same issue.

I know it seems very obvious but have you cleared the NVRAM and tried again?

**Comment by frbuccoliero** [comment]
nop, maybe i can try later

**Comment by frbuccoliero** [comment]
Tried clearing nvram but nothing. Also tried updating from the usb but here another KP https://youtu.be/HtGQa3ZVseI

**Comment by attilagyorffy** [comment]
I have a similar issue, I’ve tried with a clean vanilla install, then after failing miserably, I’ve reinstalled Catalina and then used the software update tool to upgrade to Big Sur but getting a kernel panic. I’m on the FHD version as well, so figured the screen patch wasn’t necessary. My EFI is almost identical to @jaromeyer’s, with a single exception that I have regenerated my serial and other machine-specific numbers.

**Comment by chris54721** [comment]
Try setting `Misc -> Security -> SecureBootModel` to `Disabled` in `config.plist`. Although this should not be needed with OpenCore 0.6.3, so this might be a different issue.

**Comment by frbuccoliero** [comment]
Will try this later, but if it’s not needed in 0.6.3 I have little hopes. If it can help you to help me I have some updates: using a clean efi from the repo I was able to install it. Now in the opencore picker I have only macOS entry and no more installers entries, but here the problem again:
- if I boot it from my opencore efi, I get this kernel panic: https://youtu.be/McWsodKZ9uI
- if I boot from jaro clean efi I get this super quick strange Kp: https://youtu.be/JZDryuUyQz8
I’m very angry...

**Comment by chris54721** [comment]
The second KP looks very similar to the one I fixed with that change, so it could be worth a try.

**Comment by frbuccoliero** [comment]
Ok I try asap then, I will need to change the plist from windows , any program to do it without corrupting it?

**Comment by chris54721** [comment]
Any (proper) text editor will do, it's an XML file

**Comment by frbuccoliero** [comment]
Ok i did the change and I also enabled verbose but still a kernel panic: https://youtu.be/JZDryuUyQz8

**Comment by Fyobl** [comment]
So...

I used your config.plist with updated Kexts and it booted into both Bis Sur and Windows.

I also updated my own boot loader to 0.6.3 and Kexts and it still booted.

**Comment by frbuccoliero** [comment]
> So...
> 
> I used your config.plist with updated Kexts and it booted into both Bis Sur and Windows.
> 
> I also updated my own boot loader to 0.6.3 and Kexts and it still booted.

Really?? No way. Could you give me back the whole EFI you built around my config? Maybe i misplaced something...

**Comment by frbuccoliero** [comment]
Updates:

- Remove NoTouchId from /Kexts and in config, since Dortania reports it being broken on Big Sur
- Edit csr-active-config da ZwAAAA== a /w8AAA== as suggested by Dortania for Big Sur
- Added target 83 for file logging

Nothing, no log

- I removed 

```
<key>bootercfg</key>
<string>log=0 debug=0 level=0</string>
```

under boot-args

Found the logs, they don't have the verbose but this strange log:

```
00:000 00:000 OCUI: Failed to load images
00:016 00:016 OC: External interface failure, fallback to builtin - Unsupported
```

- Bring back to true the quirks: AppleCpuPmCfgLock and AppleXcpmCfgLock i did put false to follow @mr-prez guide 

Still nothing

**Comment by frbuccoliero** [comment]
Update:
A friend of mine kindly helped me building a new EFI from scratch based on the repo and on my config. I really don't know what exactly caused this issue but now I'm on Big Sur. Thanks to everybody.

**Comment by Fyobl** [comment]
Sorry I didn’t get back to you.

I’m glad you have it working 👍

**Comment by Gorbataras** [comment]
@frbuccoliero Hey, I'm still not able to get Big Sur booting. Getting a kernel panic even after doing the stuff that's recommended on the dortania guide for Big Sur. Can you share your efi?

**Comment by frbuccoliero** [comment]
[OC.zip](https://github.com/jaromeyer/XPS9570-Catalina/files/5542252/OC.zip)

Here it is. I removed serial and the other "private" codes, make sure to change them with yours

**Comment by Gorbataras** [comment]
Very odd, I still can't boot although I am not getting a kernel panic. I get past verbose boot and then get stuck on the Apple loading screen. I am curious if it's simply just my Big Sur install though because I am able to boot into Big Sur recovery partition.

**Comment by frbuccoliero** [comment]
It happened to me too. Stay on that apple loading screen for like 20 minutes, then it reboots itself and finally booting big sur works

**Comment by Gorbataras** [comment]
Is it that way on every boot?

**Comment by frbuccoliero** [comment]
Ofc no, the first one only. Prob setting up things after the update

**Comment by Gorbataras** [comment]
Alright well I had the reboot happen, but now I just get the same kernel panic I was getting as before. No idea why that's happening.

**Comment by frbuccoliero** [comment]
Try posting your verbose

**Comment by EKeepeer** [comment]
> Update:
> A friend of mine kindly helped me building a new EFI from scratch based on the repo and on my config. I really don't know what exactly caused this issue but now I'm on Big Sur. Thanks to everybody.

Hello. I cstill can't boot install of Big Sur even. Could you share your EFI?

**Comment by frbuccoliero** [comment]
It's a couple messages up here.

**Comment by EKeepeer** [comment]
Actually thank you. I've used your OC with patch on 4k dispaly - and installation is ok.
So I am making Time machine copy now to update my Catalina system.

**Comment by EKeepeer** [comment]
It is working with your config!!!! Amazing!
I have only one issue - keyboard is not working but touchpad is ok. Backlite of keys is working. I have to use external keyboard. Could you advice hoe to fix it?

**Comment by Fyobl** [comment]
Sounds like your missing a kext...

Can you post your Kexts list?

**Comment by EKeepeer** [comment]
<img width="941" alt="Снимок экрана 2020-11-16 в 11 01 18" src="https://user-images.githubusercontent.com/51609601/99226617-1bb42f00-27fb-11eb-9b16-e2a90946b591.png">

**Comment by EKeepeer** [comment]
I've transferred my previous kexts totally from Catalina - the same.
So what can be in config about keyboard?

**Comment by Fyobl** [comment]
What version of opencore you using?

Have you updated all Kexts to latest?

**Comment by EKeepeer** [comment]
0.6.3
All kexts are updated
Hmmmmm.

**Comment by Gorbataras** [comment]
@frbuccoliero I'm not getting any KP logs saved.

**Comment by Fyobl** [comment]
@EKeepeer i just checked and can see you have a few none updated Kexts.

When updating the voodoo Kexts make sure you update them all from the same package.

<img width="943" alt="Screenshot 2020-11-16 at 08 59 33" src="https://user-images.githubusercontent.com/66086323/99236034-90cd3780-27ee-11eb-92cb-22ccdeede186.png">

Here’s a run down of the newest versions.

**Comment by frbuccoliero** [comment]
> @frbuccoliero I'm not getting any KP logs saved.

See [here](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/debug.html#config-changes)

**Comment by Gorbataras** [comment]
@frbuccoliero Are you using debug or release?

**Comment by Fyobl** [comment]
@EKeepeer also once you have made the changes make sure to clear NVRAM.

**Comment by frbuccoliero** [comment]
> @frbuccoliero Are you using debug or release?

I used release but debug would give more info of course

**Comment by Gorbataras** [comment]
@frbuccoliero 

[
[opencore-2020-11-16-094914.txt](https://github.com/jaromeyer/XPS9570-Catalina/files/5545454/opencore-2020-11-16-094914.txt)
](url)

**Comment by EKeepeer** [comment]
All kexts are actual - checked.
I tried to analyze Voodoo kexts and found out interesting things:
1. No SSDT-PS2K.aml in ACPI. Should it be there?
2. Here is on screenshot from config by frbuccoliero - not working keyboard for me.
<img width="977" alt="Снимок экрана 2020-11-16 в 12 45 11" src="https://user-images.githubusercontent.com/51609601/99241553-11039500-280f-11eb-9e54-6bdfc642c813.png">
3. If i clear all Voodoo kexts in OC Configurator and add kexts by myself then I get
<img width="992" alt="Снимок экрана 2020-11-16 в 13 19 35" src="https://user-images.githubusercontent.com/51609601/99241702-43ad8d80-280f-11eb-860f-0fc5c8fa02ce.png">

But in this case no Big Sur boot at all.

**Comment by EKeepeer** [comment]
My last chance was to update Voodoo kexts from official repo.
I didn't do it due to problems with touchpad - very ugly work.
Only kexts by LuletterSoul were perfect.

But in this case my keyborad begun to work.
So I will test touchpad then.

**Comment by Fyobl** [comment]
> All kexts are actual - checked.
> I tried to analyze Voodoo kexts and found out interesting things:
> 
> 1. No SSDT-PS2K.aml in ACPI. Should it be there?
> 2. Here is on screenshot from config by frbuccoliero - not working keyboard for me.
> 
> <img alt="Снимок экрана 2020-11-16 в 12 45 11" width="977" src="https://user-images.githubusercontent.com/51609601/99241553-11039500-280f-11eb-9e54-6bdfc642c813.png">
> 
> 3. If i clear all Voodoo kexts in OC Configurator and add kexts by myself then I get
> <img alt="Снимок экрана 2020-11-16 в 13 19 35" width="992" src="https://user-images.githubusercontent.com/51609601/99241702-43ad8d80-280f-11eb-860f-0fc5c8fa02ce.png">
> 
> But in this case no Big Sur boot at all.

With the second picture your see there 2 VoodooInput.kext I remember when I had both as enabled in config it wouldn’t boot into Big Sur so I disabled one of them.

Give this a try.

**Comment by techsnakebo** [comment]
After read all of your posts and your experiences  I'm wondering if there is a files compilation and some step by step tutorial to upgrade safely to bigsur

Thanks a lot

**Comment by EKeepeer** [comment]
Actually there is OC.zip by frbuccoliero (respect for work).
It is working with patch for 4k for me.

**Comment by techsnakebo** [comment]
is That patch the original config_4k.plist by jaromeyer ?
if yes.. did you made additional modifications to that plist?

**Comment by frbuccoliero** [comment]
My OC efi is not Jaro's . It has been made from scratch based on OC 0.6.3 since Jaro's is over OC 0.5.1 and Big Sur 11.0.1 will not work under that older OC version, at least for me

**Comment by eeonee** [comment]
Can you post the OC ?

**Comment by BearXVibes** [comment]
> My OC efi is not Jaro's . It has been made from scratch based on OC 0.6.3 since Jaro's is over OC 0.5.1 and Big Sur 11.0.1 will not work under that older OC version, at least for me

Can you post the OC ? zip folder?

**Comment by frbuccoliero** [comment]
Its's [here](https://github.com/jaromeyer/XPS9570-Catalina/issues/52#issuecomment-727552687)

**Comment by EKeepeer** [comment]
4k patch for config.plist is here https://github.com/jaromeyer/XPS9570-Catalina/issues/50 
I've got stucked boot without it.

**Comment by zhongmax** [comment]
> [OC.zip](https://github.com/jaromeyer/XPS9570-Catalina/files/5542252/OC.zip)
> 
> Here it is. I removed serial and the other "private" codes, make sure to change them with yours

It works for FHD
Thank you so much : >

**Comment by techsnakebo** [comment]
> Update:
> A friend of mine kindly helped me building a new EFI from scratch based on the repo and on my config. I really don't know what exactly caused this issue but now I'm on Big Sur. Thanks to everybody.

Is your wifi/bt a broadcom card or is it intel??

**Comment by techsnakebo** [comment]
> Its's [here](https://github.com/jaromeyer/XPS9570-Catalina/issues/52#issuecomment-727552687)

is this EFI for a broadcom wifi card ? mine is BCM4360

**Comment by frbuccoliero** [comment]
I have a DW1820A

**Comment by techsnakebo** [comment]
Someone safely upgraded from catalina to bigsur using opencore 0.6.4 new patches??
and with 4K screen?

**Comment by jaromeyer** [comment]
@techsnakebo check out [this repo](https://github.com/xxxzc/xps15-9570-macos). just follow the instructions and you shouldn't be having any problems
