### ISSUE TITLE
Big Sur Freezing and Resetting 

### ISSUE THREAD

**Issue by fireklomea** [jaromeyer/XPS9570-Catalina#53]
Hi, 
I just updated from Catalina to big sur, initially it wasn't updating, then in removed NoTouchID and it updated easily. 
Now, my 4K laptop display stays black after it has installed. I attached it to an external screen but immediately after login. The system just freezes and resets.
Is this an issue with EDID injection and is there a guide on how to do it or is this something else?
Thanks

**Comment by yudshj** [comment]
same issue here

**Comment by fireklomea** [comment]
Hi, 
I just wanted to update everyone who has this issue. I solved the issue. I just patched my EDID with the following link, it's quite easy to follow:
https://www.tonymacx86.com/threads/solved-guide-workaround-for-cdfon.306154/
The only issue is that I believe the refresh rate is 48hz. Is there any fixes for this?

**Comment by fireklomea** [comment]
Also, i can't seem to make the external display work anymore. The main laptop display is working fine, the external display is just coming black. Do I have to add the EDID for this display as well? And is it added in the same way with AAPL00,override?

**Comment by fireklomea** [comment]
Hi,
False alarm, the HDMI external screen is working alright, there was just an issue with the screen itself.
The only thing i'm wondering now is that whether it is possible to run the laptop 4K screen at full 60hz?

**Comment by Fyobl** [comment]
It’s not possible at the moment I believe... only 48mhz
