### ISSUE TITLE
Big Sur KP (missing itlwm?)

### ISSUE THREAD

**Issue by ste362** [jaromeyer/XPS9570-Catalina#57]
When I start big sur the progress bar stops the dispay flashing a litle bit and after this reboot. Were is the problem?

**Comment by Fyobl** [comment]
Have you got the 4K screen?

**Comment by ste362** [comment]
No full hd

**Comment by Fyobl** [comment]
Does it show anything when you run it in verbose mode?

**Comment by ste362** [comment]
One week ago yes but I tried a lot of EFI and now with jaromeyer not start nothing

**Comment by jaromeyer** [comment]
try the EFI.zip @frbuccoliero posted in #52

**Comment by ste362** [comment]
I already tried with this. BigSur start just one times at the second start do the same error
[panic-2020-11-27-154200.txt](https://github.com/jaromeyer/XPS9570-Catalina/files/5608352/panic-2020-11-27-154200.txt)

**Comment by jaromeyer** [comment]
what wifi card are you using?

**Comment by ste362** [comment]
intel 9260

**Comment by jaromeyer** [comment]
well, that aint gonna work without modifying the EFI. disable wifi and BT in your BIOS and try again.

**Comment by ste362** [comment]
THANKS now work!!!!! But for use WiFi what i do?

**Comment by Fyobl** [comment]
Check here this might help

https://github.com/OpenIntelWireless/itlwm

**Comment by ste362** [comment]
Ok Thank at all for the support. But why at Kevin Shroff start with Intel9260?

**Comment by jaromeyer** [comment]
he mentioned that he did some changes for his intel card
