### ISSUE TITLE
SD card reader

### ISSUE THREAD

**Issue by Fyobl** [jaromeyer/XPS9570-Catalina#59]
Haven’t needed to use this before so never noticed it but I have started playing around with Raspberry Pi hardware and wanted to flash a SD card but when I plug into the laptop I get nothing...

anyone had this issue?

Did I miss something from the configuration?

**Comment by frbuccoliero** [comment]
Have you installed the Sinatek kext and added the  -rtsx_mimic_linux  flag in boot args?

**Comment by Fyobl** [comment]
@frbuccoliero 

No...

I don’t remember seeing this on the guide.

Where do I find all this?

**Comment by frbuccoliero** [comment]
It probably shoud have been included in the readme but it wasn't. Does it work now?

**Comment by Fyobl** [comment]
@frbuccoliero 

Looks like I already had the kext on my EFI so I just added the boot arg -rtsx_mimic_linux but still not seeing it on either windows or Mac OS.

**Comment by frbuccoliero** [comment]
It is pretty strange. It should work in windows at least. For me it worked in windows before applying the kext. Make sure it’s all right
Il 29 gen 2021, 20:14 +0100, Fyobl <notifications@github.com>, ha scritto:

**Comment by Fyobl** [comment]
I’m convinced it’s my SD port possibly damaged.

nothings I’m doing seems to see it.

can you show me it in your device managers list on windows?

**Comment by frbuccoliero** [comment]
I don’t have windows anymore
Il 29 gen 2021, 21:16 +0100, Fyobl <notifications@github.com>, ha scritto:

**Comment by Fyobl** [comment]
@frbuccoliero 

Well for now I’m going to buy a SD card reader.

thanks anyway 👍

**Comment by frbuccoliero** [comment]
You're welcome. Close the issue

**Comment by jaromeyer** [comment]
also check if you havent disabled it in the BIOS, but if it doesnt work on windows its not a kext issue

**Comment by Fyobl** [comment]
@jaromeyer thats a valid point! I’ll check this and report back!

**Comment by Fyobl** [comment]
@jaromeyer 
@frbuccoliero 

It was disabled in BIOS. All sorted thank you guys 💯
