### ISSUE TITLE
Dimmed Brightness on boot OC 0.6.6

### ISSUE THREAD

**Issue by saadqazi1994** [jaromeyer/XPS9570-Catalina#60]
Hello, 
I upgraded to OC 0.6.6 but every time I boot my 9570 hackintosh into big sur, my screen is completely dimmed, extremely low brightness that cannot even be influenced by the brightness keys. Nothing seems to raise the brightness.
I have to put the computer to sleep by pressing the power button, close the lid of my screen, wait till all the fans turn off and then open the lid again. This is the only temporary fix I've found for this problem. 
By the way, i have 9570 4K display variant and I have also added the display patch in my config.plist
Please let me know what can be done to resolve this issue.

**Comment by jaromeyer** [comment]
hey, i have just updated everything to OC 0.6.6 and I'm currently working on updating this repo. Maybe give it a try once I've uploaded everything. also try a NVRAM reset

**Comment by Fyobl** [comment]
@jaromeyer 

And he’s back!

looking forward to seeing what happens next on here 👍

**Comment by saadqazi1994** [comment]
Okay, thanks a lot. I’ll wait for your update

**Comment by saadqazi1994** [comment]
With the new update, my problem has been solved. 
Thanks
