### ISSUE TITLE
Mapping keyboard issue

### ISSUE THREAD

**Issue by khoa-nv** [jaromeyer/XPS9570-Catalina#62]
I cannot type ` and ˜, it replaced by § and ±. Did anyone get the same problem with me? and how can I fix this?

**Comment by toonvanstrijp** [comment]
@khoa-nv how did you fix it?

**Comment by khoa-nv** [comment]
> @khoa-nv how did you fix it?

Change the keyboard type to ISO (European) can fix it. Go to the System preferences => Keyboard => Change keyboard type, and select ISO (European) at the last step.

**Comment by wtdcode** [comment]
> > @khoa-nv how did you fix it?
> 
> Change the keyboard type to ISO (European) can fix it. Go to the System preferences => Keyboard => Change keyboard type, and select ISO (European) at the last step.

Strange, I never get this problem in some other config. Did you figure out why the keyboard layout is wrong?
