### ISSUE TITLE
keyboard issue: type ~ but shows ±

### ISSUE THREAD

**Issue by yudshj** [jaromeyer/XPS9570-Catalina#63]
When I want to type ~, MacOS shows ± for me.
Both in terminal and text editor.
Maybe it  is related to the keyboard layout?

**Comment by jaromeyer** [comment]
the easiest way to remap certain keys is to do it inside macOS using [Karabiner](https://karabiner-elements.pqrs.org)

**Comment by yudshj** [comment]
> the easiest way to remap certain keys is to do it inside macOS using [Karabiner](https://karabiner-elements.pqrs.org)

Thanks. According to Karabiner-EventViewer, the reason is that `grave_accent_and_tilde` mapped to `non_us_backslash`.

**Comment by jaromeyer** [comment]
You could also do it in the `SSDT-PS2K.aml` but I prefer only doing basic remapping there (swap alt and cmd, function keys, fix play/pause while using Karabiner) and more high level stuff for your keyboard layout with Karabiner.

**Comment by jaromeyer** [comment]
@maghsk btw #62 is the same exact issue and probably the correct way of fixing it
