### ISSUE TITLE
iMessage not working but other services do work

### ISSUE THREAD

**Issue by frbuccoliero** [jaromeyer/XPS9570-Catalina#7]
Hi guys, i'm currently writing from my Dell XPS 9570 running a smooth Catalina 10.15.4 with everything working fine.

I replaced my stock Killer wifi card with a DW1820a that i know isn't the best but does its job. Infact wifi speed is great, bluetooth works fine and i have all BT/WiFI Apple's magic stuff working: Handoff, Continuity and Airdrop. App Store works fine too and iCloud sync is smooth.

It would have been a dream if only... iMessage doesn't work. The error is the classic one.

![kvjdszzue8u41](https://user-images.githubusercontent.com/14348908/79985063-52ff6f00-84aa-11ea-811d-3a45112abd3e.png)

It's in italian but you know, the classic one...

Here's the situation:

1. I checked the network interface, and yes, it's set to en0 and built in

![qkgkaoh4f8u41](https://user-images.githubusercontent.com/14348908/79985083-5f83c780-84aa-11ea-9baa-c6199126ad44.png)

2. I generated serial, smbios and board number and put them in config.plist , i copied the mac address and put in ROM removing the :

The serial is "invalid" in checkcoverage.apple.com because i spent half an hour trying to get a "Purchase Date not Validated:" without succcess so i surrendered using this one

![fpgrs61sf8u41](https://user-images.githubusercontent.com/14348908/79985103-67dc0280-84aa-11ea-85aa-8d7941944317.png)

Don't know if it's worth covering them but...

3. Deleted all icloud and imessage things from Library/Cache and Library/Preferences , cleared NVRAM and deleted all references from Keychain, rebooted multiple times

Still stuck at the same error. I hope you guys can help me :D

**Comment by attilagyorffy** [comment]
I have the same issue, clered NVRAM, used the same PlatformInfo values as I used previously (using back then Clover)

**Comment by frbuccoliero** [comment]
I don't understand
1. if you did solve
2. if you went back to clover

**Comment by attilagyorffy** [comment]
3. none of the above. I had Clover where iMessage was working. Now, using this repository and OC, I replaced the values in `config.plist` with the values I had in the previous Clover config, hoping to be able to get the same functionality but it does not seem to work.

**Comment by frbuccoliero** [comment]
I got it, looks like OC config is missing something from clover's...

**Comment by frbuccoliero** [comment]
Maybe you can try reporting your issue [here](https://github.com/acidanthera/bugtracker/issues) to OC creators and link this other discussion there so they can see it.

**Comment by jaromeyer** [comment]
I don't think its an issue in OC itself, but rather a misconfigured setup.

**Comment by attilagyorffy** [comment]
I managed to get iMessage up and running, however it seems to "forget" the account I've added after a while. (Not sure if that's happening after a reboot or whether it's related to an NVRAM reset though)

**Comment by frbuccoliero** [comment]
What changes did you make in order to make it work?

**Comment by attilagyorffy** [comment]
It seems that it's not working actually after a reboot.

**Comment by frbuccoliero** [comment]
But just for interest, what did you do?

**Comment by attilagyorffy** [comment]
I rebooted my machine, it seems to have logged out by itself.

**Comment by frbuccoliero** [comment]
No i mean, what did you do to make it work in the first time?

**Comment by attilagyorffy** [comment]
I regenerated the documented 3 values via Hackintool and replaced my original entries in `config.plist`, removed the iMessage related files from caches, rebooted, reset NVRAM.

**Comment by frbuccoliero** [comment]
I understand.. so nothing changed at all btw, it kicked you out...

**Comment by attilagyorffy** [comment]
It seems so

**Comment by frbuccoliero** [comment]
I solved following this: https://dortania.github.io/OpenCore-Desktop-Guide/post-install/iservices.html

I was missing the part in which it says to delete the Keychain values. It was absent in all the other guides. I also changed serial, MLB and UUID to make sure it makes no problem. All working dudes!

**Comment by attilagyorffy** [comment]
Thanks @frbuccoliero I'll try it out.
